create table Users (id INT(11) UNSIGNED generated by default as identity, first_Name varchar(255) not null, last_Name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint generated by default as identity, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id))
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
create table users (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, primary key (id)) engine=InnoDB
